// Offline import of Three.js's MIT-licensed, 4096-sample/texel DFG LUT.
import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const source=resolve(process.argv[2] ?? '../modeling-playground/node_modules/three/src/renderers/shaders/DFGLUTData.js');
const {getDFGLUT}=await import(pathToFileURL(source));
const values=Array.from(getDFGLUT().image.data,half=>{
  const exponent=(half>>10)&31, fraction=half&1023;
  return (half&32768?-1:1)*(exponent?1+fraction/1024:fraction/1024)*2**(exponent?exponent-15:-14);
});
const entries=[];for(let i=0;i<values.length;i+=2)entries.push(`    #|  vec2<f32>(${values[i].toPrecision(10)}, ${values[i+1].toPrecision(10)}),`);
const shader=`///|\n// Generated by examples/games/iron_yard/scripts/import-dfg.mjs.\n// Three.js DFG LUT (MIT); see THIRD_PARTY.md. Do not edit the table manually.\nfn dfg_wgsl() -> String {\n  let source =\n    #|const DFG_LUT = array<vec2<f32>, 256>(\n${entries.join('\n')}\n    #|);\n    #|fn environment_dfg(roughness: f32, ndotv: f32) -> vec2<f32> {\n    #|  let p = clamp(vec2<f32>(roughness, ndotv) * 16.0 - 0.5, vec2<f32>(0.0), vec2<f32>(15.0));\n    #|  let lo = vec2<u32>(floor(p));\n    #|  let hi = min(lo + vec2<u32>(1u), vec2<u32>(15u));\n    #|  return mix(mix(DFG_LUT[lo.y*16u+lo.x], DFG_LUT[lo.y*16u+hi.x], fract(p.x)),\n    #|             mix(DFG_LUT[hi.y*16u+lo.x], DFG_LUT[hi.y*16u+hi.x], fract(p.x)), fract(p.y));\n    #|}\n    #|\n  source\n}\n`;
await writeFile(new URL('../../../../engine/kagura_engine/draw3d/dfg.mbt',import.meta.url),shader);
await writeFile(new URL('../tests/dfg-reference.json',import.meta.url),JSON.stringify({source:'Three.js 0.185.1 DFGLUTData.js (MIT)',width:16,height:16,values}));
