import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {existsSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {generateSources} from './generate.mjs';

const directory = import.meta.dirname;
const root = resolve(directory, '../..');

export function sourceHash() {
  const hash = createHash('sha256');
  hash.update('../moon.mod\0').update(readFileSync(resolve(directory, '../moon.mod'))).update('\0');
  for (const name of readdirSync(directory).filter(name =>
    ['moon.pkg', 'exports.d.ts'].includes(name) || (name.endsWith('.mbt') && !/_(?:wbtest|test)\.mbt$/.test(name))).sort()) {
    hash.update(name + '\0').update(readFileSync(resolve(directory, name))).update('\0');
  }
  return hash.digest('hex');
}

export function buildCli({check = false} = {}) {
  generateSources({check});
  const result = spawnSync('moon', ['build', 'cmd/kagura', '--target', 'js', '--release'], {cwd: root, stdio: 'inherit'});
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error('Kagura CLI compilation failed');
  const artifact = resolve(root, '_build/js/release/build/mizchi/kagura_cli/kagura/kagura.js');
  const source = '// Generated by just cli-build. DO NOT EDIT.\n' +
    `// Source SHA-256: ${sourceHash()}\n` + readFileSync(artifact, 'utf8');
  const output = resolve(directory, 'cli.generated.js');
  const declarations = readFileSync(resolve(directory, 'exports.d.ts'), 'utf8');
  const pending = [[output, source], [resolve(directory, 'cli.generated.d.ts'), declarations]]
    .filter(([file, content]) => !existsSync(file) || readFileSync(file, 'utf8') !== content);
  if (check && pending.length) throw new Error('CLI is stale. Run just cli-build.');
  for (const [file, content] of pending) writeFileSync(file, content);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  buildCli({check: process.argv.includes('--check')});
}
