import {gzipSync} from 'node:zlib';
import {existsSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {resolve, join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {buildSync} from 'esbuild';
import {WEB_RUNTIME_FILES} from '../../scripts/web-runtime-assets.mjs';

const directory = import.meta.dirname;

function compress(source) {
  const compressed = gzipSync(source, {level: 9});
  // RFC 1952: OS = 255 (unknown) keeps generated sources identical on macOS and Linux.
  compressed[9] = 255;
  return compressed.toString('base64');
}

function templateEntry([path, content]) {
  const pair = `${JSON.stringify(path)}, ${JSON.stringify(content)}`;
  const line = `  (${pair}),`;
  return line.length <= 80 ? line : `  (\n    ${pair},\n  ),`;
}

function stringBinding(name, value) {
  const chunks = [];
  for (let offset = 0; offset < value.length; offset += 4096) chunks.push(JSON.stringify(value.slice(offset, offset + 4096)));
  return `let ${name} : String = ${chunks.join(' +\n  ')}\n`;
}

export function runtimeFiles() {
  return Object.fromEntries([
    ...WEB_RUNTIME_FILES.map(name => [`runtime/${name}`, readFileSync(resolve(directory, '../../assets/web', name), 'utf8')]),
    ['runtime/NOTICE', 'Kagura browser runtime\nhttps://github.com/mizchi/kagura\nSPDX-License-Identifier: Apache-2.0\nhttps://www.apache.org/licenses/LICENSE-2.0\n'],
  ]);
}
export function generatedSources() {
  const templates = resolve(directory, 'templates/web');
  const entries = readdirSync(templates).filter(name => name.endsWith('.template')).sort()
    .map(name => [name.slice(0, -9), readFileSync(join(templates, name), 'utf8')]);
  const entry = `
import {executeRequest} from './host.mjs';
import {resolve, dirname} from 'node:path';
import {gunzipSync} from 'node:zlib';
const payload = JSON.parse(process.argv[1]);
try {
  process.exitCode = await executeRequest(payload.request, {
    files: payload.files,
    runtime: payload.request.command === 'new' ? JSON.parse(gunzipSync(Buffer.from(payload.runtime, 'base64'))) : {},
    checkoutRoot: resolve(dirname(process.argv[2]), '../..'),
  });
} catch (error) { console.error('kagura: ' + error.message); process.exitCode = error.exitCode ?? 1; }
`;
  // Bundle only our host and generated MoonBit logic. Playwright is optional and
  // resolved from the caller at runtime. Compression keeps native argv bounded.
  const bundle = buildSync({stdin: {contents: entry, resolveDir: directory, sourcefile: 'installed-host.mjs'},
    absWorkingDir: resolve(directory, '../..'), bundle: true, platform: 'node', target: 'node24',
    format: 'esm', write: false, minify: true, legalComments: 'none', charset: 'utf8'}).outputFiles[0].text;
  const host = `import {gunzipSync} from 'node:zlib';\nawait import('data:text/javascript;base64,' + gunzipSync(Buffer.from(${JSON.stringify(compress(bundle))}, 'base64')).toString('base64'));\n`;
  return {
    'templates_generated.mbt': '// Generated by just cli-build. DO NOT EDIT.\n\n///|\nlet web_template_files : Array[(String, String)] = [\n' +
      entries.map(templateEntry).join('\n') + '\n]\n',
    'embedded_host_native.mbt': '// Generated by just cli-build. DO NOT EDIT.\n\n///|\n' + stringBinding('node_host', host) +
      '\n///|\n' + stringBinding('runtime_payload', compress(JSON.stringify(runtimeFiles()))),
  };
}
export function generateSources({check = false} = {}) {
  for (const [name, text] of Object.entries(generatedSources())) {
    const file = join(directory, name);
    if (existsSync(file) && readFileSync(file, 'utf8') === text) continue;
    if (check) throw new Error('CLI embedded sources are stale. Run just cli-build.');
    writeFileSync(file, text);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) generateSources({check: process.argv.includes('--check')});
