import {gzipSync} from 'node:zlib';
import {existsSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {resolve, join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {WEB_RUNTIME_FILES} from '../../scripts/web-runtime-assets.mjs';

const directory = import.meta.dirname;

function runtimePayload() {
  const compressed = gzipSync(JSON.stringify(runtimeFiles()), {level: 9});
  // RFC 1952: OS = 255 (unknown) keeps generated sources identical on macOS and Linux.
  compressed[9] = 255;
  return compressed.toString('base64');
}

function templateEntry([path, content]) {
  const pair = `${JSON.stringify(path)}, ${JSON.stringify(content)}`;
  const line = `  (${pair}),`;
  return line.length <= 80 ? line : `  (\n    ${pair},\n  ),`;
}

export function runtimeFiles() {
  return Object.fromEntries([
    ...WEB_RUNTIME_FILES.map(name => [`runtime/${name}`, readFileSync(resolve(directory, '../../assets/web', name), 'utf8')]),
    ['runtime/NOTICE', 'Kagura browser runtime\nhttps://github.com/mizchi/kagura\nSPDX-License-Identifier: Apache-2.0\nhttps://www.apache.org/licenses/LICENSE-2.0\n'],
  ]);
}
export function generatedSources() {
  const templates = resolve(directory, 'templates/web');
  const entries = readdirSync(templates).filter(name => name.endsWith('.template')).sort()
    .map(name => [name.slice(0, -9), readFileSync(join(templates, name), 'utf8')]);
  const host = readFileSync(join(directory, 'process.mjs'), 'utf8') + '\n' +
    readFileSync(join(directory, 'host.mjs'), 'utf8').replace("import {runProcess} from './process.mjs';", '') + `
import {gunzipSync} from 'node:zlib';
const payload = JSON.parse(process.argv[1]);
try {
  process.exitCode = await executeRequest(payload.request, {
    files: payload.files,
    runtime: payload.request.command === 'new' ? JSON.parse(gunzipSync(Buffer.from(payload.runtime, 'base64'))) : {},
    checkoutRoot: resolve(dirname(process.argv[2]), '../..'),
  });
} catch (error) { console.error('kagura: ' + error.message); process.exitCode = error.exitCode ?? 1; }
`;
  return {
    'templates_generated.mbt': '// Generated by just cli-build. DO NOT EDIT.\n\n///|\nlet web_template_files : Array[(String, String)] = [\n' +
      entries.map(templateEntry).join('\n') + '\n]\n',
    'embedded_host_native.mbt': '// Generated by just cli-build. DO NOT EDIT.\n\n///|\nlet node_host : String = ' + JSON.stringify(host) + '\n\n///|\nlet runtime_payload : String = ' +
      JSON.stringify(runtimePayload()) + '\n',
  };
}
export function generateSources({check = false} = {}) {
  for (const [name, text] of Object.entries(generatedSources())) {
    const file = join(directory, name);
    if (existsSync(file) && readFileSync(file, 'utf8') === text) continue;
    if (check) throw new Error('CLI embedded sources are stale. Run just cli-build.');
    writeFileSync(file, text);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) generateSources({check: process.argv.includes('--check')});
