import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {parseMotionFbx,serializeMotionSource,restoreMotionSource} from '../../../../scripts/motion/fbx.mjs';
import {emitMoonBitClip} from '../../../../scripts/motion/retarget.mjs';

import {bakeGameMotion} from './bake-game-motion.mjs';

const root=new URL('../motions/',import.meta.url);
// Same anchors as procedural3d.build_biped_skeleton(default_biped_proportions).
// Prop sockets keep the spear, bow, string and nocked arrow attached to the hands.
const definitions=[
 ['root',-1,[0,0,0]],['torso',0,[0,.54,0],'Spine3'],['head',1,[0,.72,0],'Head'],
 ['left_upper_arm',1,[-.23,.68,0],'L_Shoulder','L_Elbow',[-.255,.51,.025]],
 ['left_forearm',3,[-.255,.51,.025],'L_Elbow','L_Wrist',[-.275,.35,.06]],
 ['right_upper_arm',1,[.23,.68,0],'R_Shoulder','R_Elbow',[.255,.51,.025]],
 ['right_forearm',5,[.255,.51,.025],'R_Elbow','R_Wrist',[.275,.35,.06]],
 ['left_thigh',0,[-.105,.42,0],'L_Hip','L_Knee',[-.105,.22,0]],
 ['left_shin',7,[-.105,.22,0],'L_Knee','L_Ankle',[-.105,.055,0]],
 ['right_thigh',0,[.105,.42,0],'R_Hip','R_Knee',[.105,.22,0]],
 ['right_shin',9,[.105,.22,0],'R_Knee','R_Ankle',[.105,.055,0]],
 ['tail',0,[0,.42,-.1]],['weapon',6,[.34,.36,.14]],
 ['bow',4,[-.275,.35,.06]],['bow_string',13,[-.275,.35,-.07]],['nocked_arrow',14,[-.275,.35,-.07]],
];
const profile={joints:definitions.map(([name,parent,position,source,sourceTip,tip])=>({name,parent,position,source,sourceTip,tip,aimWeapon:name==='weapon'})),
 soles:[8,10].flatMap(joint=>[-.07,.15].map(z=>({joint,position:[joint===8?-.105:.105,0,z]})))};
const edits={
 spear_thrust:{impact:1.97,aimBone:'R_Wrist',aimOrigin:'R_Shoulder'},
 punch:{impact:1.25,aimBone:'R_Wrist',aimOrigin:'R_Shoulder'},
 cast_spell:{impact:1.5,aimBone:'L_Wrist',aimOrigin:'L_Shoulder'},
 bow_shot:{impact:2.5,aimBone:'L_Wrist',aimOrigin:'L_Shoulder'},
};
let generated='// Generated by just hunter-motions-build from fal HY Motion FBX. Do not hand edit.\n';
const report={version:1,model:'fal-ai/hunyuan-motion',profile,clips:[]};
for(const [name,edit] of Object.entries(edits)){
 const receipt=JSON.parse(await readFile(new URL(`source/${name}/result.json`,root)));
 const sourcePath=new URL(`source/${name}/source-motion.json`,root);
 let serialized;
 try{serialized=JSON.parse(await readFile(sourcePath,'utf8'));}catch(e){
  if(e.code!=='ENOENT')throw e;
  const bytes=await readFile(new URL(`source/${name}/motion.fbx`,root));
  if(createHash('sha256').update(bytes).digest('hex')!==receipt.sha256)throw Error(`Source checksum mismatch: ${name}`);
  serialized={...serializeMotionSource(parseMotionFbx(bytes)),fbxSha256:receipt.sha256};
  await writeFile(sourcePath,JSON.stringify(serialized)+'\n');
 }
 if(serialized.fbxSha256!==receipt.sha256)throw Error('Motion source provenance mismatch');
 const source=restoreMotionSource(serialized),clip=source.animations[0];
 const options={name,frames:49,duration:1,start:0,end:clip.duration,contact:.5,blend:.10,mirrorX:true,...edit};
 const baked=bakeGameMotion(source,clip,profile,options);
 generated+='\n'+emitMoonBitClip(baked);
 await writeFile(new URL(`${name}.clip.json`,root),JSON.stringify(baked)+'\n');
 report.clips.push({name,requestId:receipt.requestId,sha256:receipt.sha256,sourceDuration:clip.duration,sourceSha256:createHash('sha256').update(JSON.stringify(serialized)).digest('hex'),options});
 console.log(`${name}: ${baked.frames} poses, ${baked.joints.length} joints`);
}
await writeFile(new URL('../app/enemy_motion_generated.mbt',root),generated);
await writeFile(new URL('manifest.json',root),JSON.stringify(report,null,2)+'\n');
