// WGSL files are the source of truth. Generated MoonBit only embeds/composes them.
import {readFile,writeFile} from 'node:fs/promises';
const names=['uniforms','color','cube_uv','standard','unlit','shadow','present'];
let output='// Generated by draw3d/scripts/embed-wgsl.mjs; edit shaders/*.wgsl instead.\n';
for(const name of names){
 const source=await readFile(new URL(`../shaders/${name}.wgsl`,import.meta.url),'utf8');
 output+=`\n///|\nfn standard_${name}_source() -> String {\n  let source =\n${source.trimEnd().split('\n').map(line=>`    #|${line}`).join('\n')}\n    #|\n  source\n}\n`;
}
await writeFile(new URL('../standard_sources.mbt',import.meta.url),output);
