///|
pub fn install(_title : String) -> Unit {
  ()
}

///|
pub fn uninstall() -> Unit {
  ()
}

///|
pub fn is_ready() -> Bool {
  false
}

///|
pub fn shutdown() -> Unit {
  ()
}

///|
pub fn initialize_context(_width : Int, _height : Int, _title : String) -> Bool {
  false
}

///|
pub fn should_close() -> Bool {
  true
}

///|
pub fn poll_events() -> Unit {
  ()
}

///|
pub fn render_frame() -> Bool {
  false
}

///|
pub fn shutdown_context() -> Unit {
  ()
}
